fixed strange issue of missing callback in stream
still not sure exactly what was going on, but cloneDeep seemed to have
an adverse effect on things...

      Error: no writecb in Transform class
    at afterTransform (_stream_transform.js:71:33)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at StringIO.PassThrough._transform (_stream_passthrough.js:21:3)
    at StringIO.Transform._read (_stream_transform.js:167:10)
    at StringIO.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at StringIO.Writable.write (_stream_writable.js:215:11)
    at Logger._emit (/.../carbon-log/node_modules/bunyan/lib/bunyan.js:924:24)
    at Logger.warn (/.../carbon-log/node_modules/bunyan/lib/bunyan.js:1050:24)